[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[BASE]
source = "container"
container = "library/alpine"
include_regex = "\\d+\\.\\d+\\.?\\d?"

[ETCD]
source = "github"
github = "etcd-io/etcd"
use_max_tag = true
prefix = "v"
exclude_regex = ".*(alpha|beta).*"
